version: '2'
services:
  odoo:
    build: 
        context: .
        dockerfile: ./odoo/Dockerfile
    restart: always
    ports:
      - "8079:8069"
    links:
      - db
    volumes:
      - ./extra-addons:/mnt/extra-addons
  db:
    image: postgres:10
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    volumes:
      - ./backup:/mnt/backup
